apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    credentials: AgBWeA2LoJZ75nGjrhS/Ux5nWHR1WlUibje18fKdOdqyz+WpfXA4wsBH8XvnnAUFy46fMeiGtQj9ZcUguN8si6qG3YDokaqGsxSZ66Fozyv9rMGd6z7s/5V3y62/QXtPf9YkzptXdMasLJF0jJ56RPNmyLnh6AMIAx5zq1cnAjyO1X0rUVzfi1Ljx2C8YoIpnEBmexjyYuI96yuIESEQ3cgf8g83BX39Mehw5ZHBYUCCftg+9u2TcEx8rJPDA9EkudIFHH/OajtQMO6UX2AHSb/K2WqUlRLBbsnKIZFq6GlAevRj29YDADc46jZ61F1AtSuT97ffZwzfROZJvP4k89Gs52/8Q2l0r1cNwB6t5Djw2hd195pgm+Dg7Ae/s+/eMXiPlkocd2zjsVVoJjF9pZp3ZZzcOBgeSZIPENmoZgFIAtJ+cKnuPNnNCMSzRYqDEZcjj9+NkYQFlas+XIM3TkDNjs9OHEE2udIgbTNqHcms0rXJd01sKdciHZEHdKEV1lKbJauBJlXphevWN3iqEsy6QmFJKA7mGBFoQ3i+BiDgAJYOgVThV1MvvjM7kTjoMp6y8u84utM0eOTvP0EgSqLcPAsocVD/Do6x/zhO9FABch90kcXe2AMUFY4sewl/HYv2Uyq9cFcVnxOIrbWyRfpkNOGubNoLZTgZ2U2liuMj2QTE4s0XdATDOti2WY8mi0IDiQRavN/a/jJdJJhCGg8z+qObCvtua0hsrn19j9yr1zLy+K9vJzSA2F4Oy9mF886xL0oJJ4bWyv4dTXNP3s49lDeLFF4CaQYanBaQ6IDul6VeEIvI4d2Fs+KYlN0sA4dzoJhlDRWG5efuXUB4XQRzyY8NGgG/CgNYW2g71TA0lmn1hhPSvQGDk9DzlZ9mij7E6wpGYfaJ3GP1SEoO1ucsmyFdy2vG8eNDFScKBqbCtmRIP+elFjF1oRnEO2oWjmn0I8uzUrxl5Z8+QP5UB8w2fUdgDsrmoOJId5rlKqhtPvAdnlAvYYQ1Mgrj1mnYOIDDyBD/Vmj4fB+8uhUjwxAPN3D0IUexSax95u1mHhpvoCyJ6YEmVr3s6mUAWQUxN/SvxI66CLLb53V1aSLM+/0oSUCn07MHlda+EE681MjbxuqDGcZQEdfO66PHdpVH+rMdDc1njTzNhA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaque

