version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: gurppup/udacity-reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: gurppup/udacity-backend-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: gurppup/udacity-backend-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: gurppup/udacity-frontend
